# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.6.9
    steps:
      - checkout
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "ci_requirements.txt" }}
      - run:
          name: install firejail cmake java go
          command: |
            sudo apt-get --allow-releaseinfo-change update
            sudo apt-get install firejail cmake default-jdk
            wget -c https://dl.google.com/go/go1.14.2.linux-amd64.tar.gz -O - | sudo tar -xz -C /usr/local
            sudo cp /usr/local/go/bin/go /usr/bin/
            go get golang.org/x/tools/cmd/goimports

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate

            pip install -U pip
            pip install -r ci_requirements.txt

            # install rust
            curl https://sh.rustup.rs -sSf > rustup.sh
            bash rustup.sh -y

            mkdir -p tree-sitter
            cd tree-sitter
            for lang in cpp rust java python javascript go
            do
                echo $lang
                [ ! -d 'tree-sitter-'$lang ] && git clone https://github.com/tree-sitter/tree-sitter-$lang.git
                (cd tree-sitter-$lang && git pull)
            done
            cd ..

            git clone https://github.com/glample/fastBPE.git
            cd fastBPE
            g++ -std=c++11 -pthread -O3 fastBPE/main.cc -IfastBPE -o fast
            python setup.py install
            cd ..
            pip install fastBPE
            pip install einops

      - save_cache:
          paths:
            - ./venv
            - ./tree-sitter
          key: v2-dependencies-{{ checksum "ci_requirements.txt" }}

      - run:
          name: install gtest
          command: |
            wget https://github.com/google/googletest/archive/release-1.8.0.tar.gz
            tar xf release-1.8.0.tar.gz
            cd googletest-release-1.8.0
            cmake -DBUILD_SHARED_LIBS=ON .
            make
            sudo cp -a googletest/include/gtest /usr/include
            sudo cp -a googlemock/gtest/libgtest_main.so googlemock/gtest/libgtest.so /usr/lib/

      - run:
          name: Print install
          command: |
            . venv/bin/activate
            pip freeze

      - run:
          name: Run black
          when: always
          command: |
            . venv/bin/activate
            black codegen_sources/. --diff
            black codegen_sources/. --check

      - run:
          name: Run pytest
          when: always
          command: |
            . venv/bin/activate
            pytest -vs codegen_sources --durations=20