/*
 * This file was automatically generated by EvoSuite
 * Wed Apr 21 13:16:53 GMT 2021
 */


import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class CLASS_9167f62308cfc555ab31a6e4dcdcc95ca2bdcab48016d16bd5b42146ef1977eb_ESTest extends CLASS_9167f62308cfc555ab31a6e4dcdcc95ca2bdcab48016d16bd5b42146ef1977eb_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      float float0 = CLASS_9167f62308cfc555ab31a6e4dcdcc95ca2bdcab48016d16bd5b42146ef1977eb.sqr(31337.701F);
      assertEquals(9.8205152E8F, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      float float0 = CLASS_9167f62308cfc555ab31a6e4dcdcc95ca2bdcab48016d16bd5b42146ef1977eb.sqr(0.0F);
      assertEquals(0.0F, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      CLASS_9167f62308cfc555ab31a6e4dcdcc95ca2bdcab48016d16bd5b42146ef1977eb cLASS_9167f62308cfc555ab31a6e4dcdcc95ca2bdcab48016d16bd5b42146ef1977eb0 = new CLASS_9167f62308cfc555ab31a6e4dcdcc95ca2bdcab48016d16bd5b42146ef1977eb();
  }
}