/*
 * This file was automatically generated by EvoSuite
 * Wed Apr 21 13:17:52 GMT 2021
 */

public class CLASS_196a45f8932c033f06f6a086488b268404e77353d16c9bc6407a417f237da6db_ESTest extends CLASS_196a45f8932c033f06f6a086488b268404e77353d16c9bc6407a417f237da6db_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      int int0 = CLASS_196a45f8932c033f06f6a086488b268404e77353d16c9bc6407a417f237da6db.missingNumber((int[]) null);
      assertEquals(0, int0);
  }