/*
 * This file was automatically generated by EvoSuite
 * Wed Apr 21 13:41:06 GMT 2021
 */


import org.junit.Test;
import static org.junit.Assert.*;
import java.util.ArrayList;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class CLASS_db35bde703321c750c7134d5769b704c9ab7f9841c6654abb814683a361f9de1_ESTest extends CLASS_db35bde703321c750c7134d5769b704c9ab7f9841c6654abb814683a361f9de1_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ArrayList<Double> arrayList0 = new ArrayList<Double>();
      Double double0 = new Double(0.0);
      arrayList0.add(double0);
      Double double1 = new Double(1.0);
      CLASS_db35bde703321c750c7134d5769b704c9ab7f9841c6654abb814683a361f9de1.ExpandArrayByLastE_Double(arrayList0, double1);
      assertFalse(arrayList0.contains(double1));
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ArrayList<Double> arrayList0 = new ArrayList<Double>();
      Double double0 = new Double(0.0);
      arrayList0.add(double0);
      CLASS_db35bde703321c750c7134d5769b704c9ab7f9841c6654abb814683a361f9de1.ExpandArrayByLastE_Double(arrayList0, double0);
      assertTrue(arrayList0.contains(0.0));
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ArrayList<Double> arrayList0 = new ArrayList<Double>();
      Double double0 = new Double(9000.554);
      arrayList0.add(double0);
      CLASS_db35bde703321c750c7134d5769b704c9ab7f9841c6654abb814683a361f9de1.ExpandArrayByLastE_Double(arrayList0, double0);
      assertEquals(9001, arrayList0.size());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ArrayList<Double> arrayList0 = new ArrayList<Double>();
      Double double0 = new Double(0.0);
      CLASS_db35bde703321c750c7134d5769b704c9ab7f9841c6654abb814683a361f9de1.ExpandArrayByLastE_Double(arrayList0, double0);
      assertFalse(arrayList0.contains(double0));
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      CLASS_db35bde703321c750c7134d5769b704c9ab7f9841c6654abb814683a361f9de1 cLASS_db35bde703321c750c7134d5769b704c9ab7f9841c6654abb814683a361f9de1_0 = new CLASS_db35bde703321c750c7134d5769b704c9ab7f9841c6654abb814683a361f9de1();
  }
}
