/*
 * This file was automatically generated by EvoSuite
 * Wed Apr 21 13:16:49 GMT 2021
 */


import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true)
public class CLASS_27c05c7602b81c3bcf7ac99abf940ebc4c909da67935bb59bc30e51ac3933ace_ESTest extends CLASS_27c05c7602b81c3bcf7ac99abf940ebc4c909da67935bb59bc30e51ac3933ace_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CLASS_27c05c7602b81c3bcf7ac99abf940ebc4c909da67935bb59bc30e51ac3933ace cLASS_27c05c7602b81c3bcf7ac99abf940ebc4c909da67935bb59bc30e51ac3933ace0 = new CLASS_27c05c7602b81c3bcf7ac99abf940ebc4c909da67935bb59bc30e51ac3933ace();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      String string0 = CLASS_27c05c7602b81c3bcf7ac99abf940ebc4c909da67935bb59bc30e51ac3933ace.getProperty("", "");
      assertNull(string0);
  }
}