/*
 * This file was automatically generated by EvoSuite
 * Wed Apr 21 13:16:57 GMT 2021
 */

public class CLASS_c2a773c670339b0d7be430a133f7f597ae56ad8ebb7f7209c0fe9edbd248fd04_ESTest extends CLASS_c2a773c670339b0d7be430a133f7f597ae56ad8ebb7f7209c0fe9edbd248fd04_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      boolean boolean0 = CLASS_c2a773c670339b0d7be430a133f7f597ae56ad8ebb7f7209c0fe9edbd248fd04.isExtension("", (String) null);
      assertFalse(boolean0);
  }